### ISSUE TITLE
Class name camel case 500 Internal Server Error

### ISSUE THREAD

**Issue by jtrolle** [crossjoin/Css#2]
i use your premailer and i have this error:
Attempted to load class "StyleSheet" from namespace "Crossjoin\Css\Format\StyleSheet"
in vendor/crossjoin/css/src/Crossjoin/Css/Reader/ReaderAbstract.php

i had to rename this file https://github.com/crossjoin/Css/blob/master/src/Crossjoin/Css/Format/StyleSheet/Stylesheet.php
to StyleSheet.php to respect the camel case between filename and class

**Comment by crossjoin** [comment]
Oh, I only tested on Windows systems. :) Just fixed it.

Thanks!
